### ISSUE TITLE
SVG rendering correctly but not PDF and ESP

### ISSUE THREAD

**Issue by eseifert** [eseifert/vectorgraphics2d#22]
Hi fellow charting lib developer!

I'm the main dev of XChart, and someone requested that I implement a vector graphics export function like Gral. (BTW, nice project!)

I was able to change a lot of my underlying code to get things compatible with vectorgraphics2d and the SVG export works great. The PDF and ESP are not so great though. I've attached some screenshots. Can you perhaps guess why the rendering isn't working properly? 

Thanks, Tim

 _Imported from trac ticket #16,  created by timmolter on 04-26-2014 at 17:16, last modified: 04-26-2014 at 17:16_

**Comment by timmolter** [comment]
I figured this out. It's not an issue with vectorgraphics2d but with Swing. When switiching storkes from a dashed stroke to a solid stroke you need to use:

    new BasicStroke(1, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 10.0f, new float[] { 3.0f, 0.0f }, 0.0f);

and not:

    new BasicStroke(1, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL);

I guess the dash doesn't get updated in the resulting `Shape` object, but setting the dash array to `3.0f, 0.0f ` is a hack to make it draw a solid line. 

Feel free to close this issue.

**Comment by seifertm** [comment]
Thanks for letting us know. This behaviour is strange indeed.

Go ahead and reopen this issue, if anything else shows up.
