### ISSUE TITLE
Multipage pdfs?

### ISSUE THREAD

**Issue by plufz** [eseifert/vectorgraphics2d#23]
Hi!

Is it possible to create multipage pdfs with vectorgraphics2d?

**Comment by eseifert** [comment]
Currently, it's not possible to create multipage PDFs with VectorGraphics2D.
I have some ideas how it could be done, but Java's Graphics2D interface has no concept of a page or a sequence of pages.

**Comment by plufz** [comment]
Ah, okay. Thanks for the quick reply!
