### ISSUE TITLE
Text encoding

### ISSUE THREAD

**Issue by plufz** [eseifert/vectorgraphics2d#24]
What does "Some features are still missing, like [..] text encoding" really mean? I'm trying to print some non-ascii characters (swedish åäö) that comes out invalid. Can I somehow output these characters by changing encoding of the text myself before using drawString()? Thanks for your time!

**Comment by eseifert** [comment]
By default Java uses UTF-8 for Strings. EPS and PDF usually rely on Latin 1, but characters like å, ä, or ö should be fine. Which version of VectorGraphics2D are you using? Can you send a source code file with a short example to dev@erichseifert.de?

**Comment by plufz** [comment]
Great. I've sent you some example code.

**Comment by eseifert** [comment]
Thanks. We tried to render extended characters like ä, ö, or å with the PDF export of the current git version and it works fine. The API should be the same as in 0.9.1, which you have been using. Could you give it a try and report back?

**Comment by plufz** [comment]
I've tried the git one eariler today but it generated an eps instead of a pdf using the pdf class. did you really get a pdf?

Mvh Emil Edeholt
Skickat från mobil

**Comment by eseifert** [comment]
Thank Emil! You're right there was a bug causing EPS files to be generated instead of PDF. I just made commit that fixes it. Can you try it again?
PDF seems to have white base color which still has to fixed, so make sure you call setColor once before drawing the text.

**Comment by eseifert** [comment]
The color issue should be resolved now. I did some more experiments myself and it seems there are still encoding problems for the mentioned letters. I will have to dig further into this.

**Comment by plufz** [comment]
Hi again! Just wanted to tell you that I had to use another library because of lack of time. So no need to hurry on the bug fix for my sake. Hope I didn't cause any trouble for you! And thanks for the quick response.

**Comment by eseifert** [comment]
As of commit 1c3e24c13e92f3a7c6cac12ae8a87af92f478435 we are using WinAnsi font encoding by default which should solve the issue. Feel free to reopen.

**Comment by JavaJens** [comment]
I experience the same issue with version 0.9.2.
Depending on the font either nothing or garbage is shown. Any help is appreciated.

**Comment by eseifert** [comment]
Thanks for the update. Yes, it should be fixed in master only so far. We didn't backport the fix to 0.9.x yet.
