### ISSUE TITLE
Support for Paint objects

### ISSUE THREAD

**Issue by eseifert** [eseifert/vectorgraphics2d#25]
After rewriting VectorGraphics2D to use objects Paint objects aren't exported correctly anymore. This should be (re-)implemented.

**Comment by seifertm** [comment]
EPS supports Paint as of commit e5a58484d8c7dfdf1de229acbf2b8c3b939452d8.
PDF supports Paint as of commit 24f5a776286fc6acb95031e9976387542a77f0c6.
