### ISSUE TITLE
Rename Document.write(OutputStream) to Document.writeTo(OutputStream)

### ISSUE THREAD

**Issue by eseifert** [eseifert/vectorgraphics2d#45]
The `write` method usually writes something *into* the object (i. e. the `Document` in this case). However, this method writes the contents of the `Document` into the specified `OutputStream`, so `writeTo` seems to be more fitting.

**Comment by seifertm** [comment]
Resolved as of commit e2967ffad4192978923b057b44b2da83fc65ef2e.
