### ISSUE TITLE
Create builder for VectorGraphics2D

### ISSUE THREAD

**Issue by eseifert** [eseifert/vectorgraphics2d#47]
Instead of creating file-format specific objects directly, such as `new SVGGraphics2D(...)`, a builder should be used.
Example:

    VectorGraphics2D vg2d = new VectorGraphics2D.Builder("svg", PageSize.A4)
        .compressed(true).build();

**Comment by seifertm** [comment]
Resolved as of commit 54b89b6a111e90ef4d8202a3d13de86d3862f047.
