### ISSUE TITLE
Fix number handling for PDF output

### ISSUE THREAD

**Issue by Greunlis** [eseifert/vectorgraphics2d#63]
PDF doesn't support real numbers in exponential notation like 6.67e−11.
Such numbers can easily occur, especially in transformations.

Other formats might support this notation.

I fixed it in DataUtils.java, since I only use one format - PDF.
Can I somehow help fixing it?

**Comment by eseifert** [comment]
Thanks for your report! I also think that fix in the ```DataUtils``` class would be the safest choice in this case. I'll commit a solution soon.

**Comment by eseifert** [comment]
Should be fixed now with commit https://github.com/eseifert/vectorgraphics2d/commit/f9428647e2f816da27265b59eb860126f31f62b3
