### ISSUE TITLE
bad /BBox in font 'Dialog.plain'

### ISSUE THREAD

**Issue by ejabarov** [eseifert/vectorgraphics2d#66]
Hello, 

Is there any way not to shows this warning in Acrobat Reader?

Thank you in advance

**Comment by eseifert** [comment]
This bug is a duplicate of #41. Please continue the conversation there. Thanks.

**Comment by ejabarov** [comment]
Thank you for your reply. Can you please provide some more information for the following case?

ProcessingPipeline g = null; g = new PDFGraphics2D(0, 0, 595, 842); chart.paint(g, view.getWidth(), view.getHeight()); try (FileOutputStream file = new FileOutputStream("test1.pdf")) { file.write(g.getBytes()); }
I am not really sure what font do you mean?

Thank you for your time
