### ISSUE TITLE
Bug in pdfProcessor when the PageSize starting y axis differs from zero?

### ISSUE THREAD

**Issue by bellaz89** [eseifert/vectorgraphics2d#72]
Here it is some example (scala) code
```scala
import java.awt.BasicStroke
import java.awt.geom.Rectangle2D
import java.io._
import de.erichseifert.vectorgraphics2d._
import de.erichseifert.vectorgraphics2d.util._

object MainTest {

	def main(args: Array[String]): Unit = {
		val vg2d = new VectorGraphics2D()
		vg2d.setStroke(new BasicStroke(2.0f))
		vg2d.drawRect(-5, -5, 10, 10)
		val commands = vg2d.getCommands()
		val pdfProcessor = Processors.get("pdf")
		val svgProcessor = Processors.get("svg")

		val doc1 = pdfProcessor.getDocument(commands, new PageSize(-10,-10,20,20))
		doc1.writeTo(new FileOutputStream("rect.pdf"))
		
		val doc2 = svgProcessor.getDocument(commands, new PageSize(-10,-10,20,20))
		doc2.writeTo(new FileOutputStream("rect.svg"))

	}
}
```

The generated pdf: 
![rect](https://user-images.githubusercontent.com/6207327/68299140-699c4000-009b-11ea-94d0-cdec9e344ace.jpg)
[rect.pdf](https://github.com/eseifert/vectorgraphics2d/files/3814417/rect.pdf)

The generated svg (converted to jpg):
![rect](https://user-images.githubusercontent.com/6207327/68299031-280b9500-009b-11ea-9f91-1e3b83bb5506.jpg)

So the pdfProcessor seems to ignore the 'y' argument of PageSize..

**Comment by eseifert** [comment]
Thanks @bellaz89! This definitely looks like a bug with page coordinates in PDFDocument and should be fixed.
