### ISSUE TITLE
 this software is only licensed under GPL?

### ISSUE THREAD

**Issue by maxpaynebupt** [eseifert/vectorgraphics2d#75]
If true, no one can use it as it is a jar file.

**Comment by eseifert** [comment]
VectorGraphics2D uses the LGPL license. It allows you to use the JAR file freely without restrictions and without affecting your own code’s license.

Here’s what David Turner from GNU writes about this topic:

> If you distribute a Java application that imports LGPL libraries, it's easy to comply with the LGPL. Your application's license needs to allow users to modify the library, and reverse engineer your code to debug these modifications. This doesn't mean you need to provide source code or any details about the internals of your application. Of course, some changes the users may make to the library may break the interface, rendering the library unable to work with your application. You don't need to worry about that—people who modify the library are responsible for making it work.
>
> When you distribute the library with your application (or on its own), you need to include source code for the library. But if your application instead requires users to obtain the library on their own, you don't need to provide source code for the library. 

Source: https://www.gnu.org/licenses/lgpl-java.html
