### ISSUE TITLE
Set an automatic module name in the Jar MANIFEST

### ISSUE THREAD

**Issue by carlosame** [eseifert/vectorgraphics2d#76]
To use this project in JPMS modular builds, an automatic module name would be helpful. See the following blog post for context:

http://branchandbound.net/blog/java/2017/12/automatic-module-name/

The idea would be to add the following to `build.gradle`:
```patch
@@ -73,10 +73,16 @@ license {
     ext.email1 = owner1_email
     ext.owner2 = owner2_name
     ext.email2 = owner2_email
 }
 
+jar {
+    manifest {
+      attributes('Automatic-Module-Name': 'de.erichseifert.vectorgraphics2d')
+    }
+}
+
 task shrinkJar(type: proguard.gradle.ProGuardTask, dependsOn: jar) {
     description = 'Uses ProGuard to reduce the code size of this project.'
     group = 'Build'
     // Configure ProGuard
     configuration("${projectDir}/src/etc/proguard.conf")
```
I'm preparing a pull request with the change.

**Comment by Brixomatic** [comment]
@eseifert : This PR would be helpful and doesn't seem to cause harm. 
Would you mind merging this and releasing it as a new version?

**Comment by eseifert** [comment]
Yes @Brixomatic, looks good to me, too. Thanks to @carlosame for the PR. I’ll have to fix the build system before I can make a new release though.
